server:
  port: 8080

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.*
      - org.springframework.boot.autoconfigure.orm.jpa.*
      - org.springframework.boot.autoconfigure.transaction.*
      - org.springframework.boot.autoconfigure.sql.*
  main:
    web-application-type: reactive
  sql:
    init:
      mode: never
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: usuarios
          uri: lb://mvc_usuario
          predicates:
            - Path=/usuarios/**

        - id: cuentas
          uri: lb://mvc_usuario
          predicates:
            - Path=/cuentas/**

        - id: monopatin
          uri: lb://mvc_monopatin
          predicates:
            - Path=/monopatines/**

        - id: paradas
          uri: lb://mvc_monopatin
          predicates:
            - Path=/paradas/**

        - id: pagos
          uri: lb://mvc_facturacion
          predicates:
            - Path=/pagos/**

        - id: tarifas
          uri: lb://mvc_facturacion
          predicates:
            - Path=/tarifas/**

        # Health checks
        - id: health-usuarios
          uri: lb://mvc_usuario
          predicates:
            - Path=/health/usuarios
          filters:
            - SetPath=/

        - id: health-monopatines
          uri: lb://mvc_monopatin
          predicates:
            - Path=/health/monopatines
          filters:
            - SetPath=/

        - id: health-facturacion
          uri: lb://mvc_facturacion
          predicates:
            - Path=/health/facturacion
          filters:
            - SetPath=/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: ERROR
    org.springframework.boot.autoconfigure.orm.jpa: ERROR
    org.springframework.cloud.gateway: DEBUG